In [1]:
import tweepy
import spacy
import en_core_web_sm
import numpy as np

In [2]:
auth = tweepy.OAuthHandler(None, None)

In [3]:
twitter = tweepy.API(auth)

In [2]:
def retrieve_keys(
    path='/Users/colby/Documents/Lambda/03 Unit 3/twitterapi.keys'
):
    """Retrieves my twitter api keys because .env files won't work"""

    file = open(
        '/Users/colby/Documents/Lambda/03 Unit 3/twitterapi.keys',
        'r'
    )

    data = file.read().split('\n')

    keys = {}

    for x in data:
        y = x.split('=')

        keys[y[0]] = y[1]

    return keys

def twit_connect(keys=retrieve_keys()):
    """Connects to twitter. Returns a tweepy.API object."""

    auth = tweepy.OAuthHandler(keys['KEY'], keys['SECRET'])
    twitter = tweepy.API(auth)

    return twitter

In [3]:
twitter = twit_connect()

In [5]:
jeff = twitter.get_user('jeffbezos')
nasa = twitter.get_user('nasa')

In [13]:
jefftwee = jeff.timeline(count=200, exclude_replies=True, include_rts=False, tweet_mode='Extended')
nasatwee = nasa.timeline(count=200, exclude_replies=True, include_rts=False, tweet_mode='Extended')

In [10]:
nlp_model = en_core_web_sm.load()

In [21]:
nlp = spacy.load('my_nlp_model')

In [18]:
nasvec = nlp_model(nasatwee[0].text).vector
jefvec = nlp_model(jefftwee[0].text).vector

In [17]:
vec = lambda text : nlp(text).vector

In [22]:
nasnlpvec = nlp(nasatwee[0].text).vector

nasnlpvec

In [20]:
nasavec = vec(nasatwee[0].text)
nasavec

array([ 3.33746195e-01,  1.55296043e-01, -9.90208685e-02,  4.33879755e-02,
        4.38914262e-02, -2.27273583e-01,  1.32762017e-02, -1.54837444e-01,
        8.34296644e-02, -9.83140841e-02,  3.55274171e-01,  1.05709374e-01,
        9.35405865e-02, -7.15809390e-02,  7.01167509e-02, -2.58716922e-02,
       -1.10203102e-02, -3.58127743e-01,  7.60852396e-02,  1.69506773e-01,
       -2.33707726e-01, -8.03387538e-02, -1.56751856e-01, -1.62821580e-02,
        9.22715068e-02, -1.93567172e-01,  7.64533356e-02, -6.15054853e-02,
       -2.58375555e-02, -8.58401060e-02, -4.11289893e-02,  1.87978223e-01,
       -2.91820139e-01,  6.25981912e-02,  4.49248701e-02,  1.11194693e-01,
       -1.14536427e-01,  1.77527424e-02, -7.56664053e-02, -4.73011844e-02,
       -4.01524343e-02,  3.81774604e-02, -2.17417561e-04,  4.44949865e-02,
        1.28540903e-01, -3.47144268e-02,  1.65407628e-01, -2.03248337e-01,
       -2.10275888e-01, -2.35162172e-02,  9.69608203e-02, -3.38508300e-02,
        1.58638880e-01,  

In [26]:
for tweet in nasatwee:
    print(tweet.text)
    print(vec(tweet.text))

LIVE: Our head of human spaceflight @KathyLueders speaks at @AirAndSpace.

🤩 Tune in for her insights on humanity's… https://t.co/Zx7i4HAMyN
[ 3.33746195e-01  1.55296043e-01 -9.90208685e-02  4.33879755e-02
  4.38914262e-02 -2.27273583e-01  1.32762017e-02 -1.54837444e-01
  8.34296644e-02 -9.83140841e-02  3.55274171e-01  1.05709374e-01
  9.35405865e-02 -7.15809390e-02  7.01167509e-02 -2.58716922e-02
 -1.10203102e-02 -3.58127743e-01  7.60852396e-02  1.69506773e-01
 -2.33707726e-01 -8.03387538e-02 -1.56751856e-01 -1.62821580e-02
  9.22715068e-02 -1.93567172e-01  7.64533356e-02 -6.15054853e-02
 -2.58375555e-02 -8.58401060e-02 -4.11289893e-02  1.87978223e-01
 -2.91820139e-01  6.25981912e-02  4.49248701e-02  1.11194693e-01
 -1.14536427e-01  1.77527424e-02 -7.56664053e-02 -4.73011844e-02
 -4.01524343e-02  3.81774604e-02 -2.17417561e-04  4.44949865e-02
  1.28540903e-01 -3.47144268e-02  1.65407628e-01 -2.03248337e-01
 -2.10275888e-01 -2.35162172e-02  9.69608203e-02 -3.38508300e-02
  1.58638880e-

In [30]:
jeff_tweets_vec = np.array([vec(tweet.text) for tweet in jefftwee])
nasa_tweets_vec = np.array([vec(tweet.text) for tweet in nasatwee])

In [29]:
jeff_tweets_vec

array([[ 0.24272835, -0.2283334 , -0.02567933, ...,  0.16770232,
        -0.03415189,  0.05669243],
       [ 0.15387794,  0.11360475,  0.16392364, ...,  0.31951156,
         0.10325204,  0.12163479],
       [ 0.09383198,  0.1428592 ,  0.02291863, ...,  0.1494844 ,
        -0.15196325,  0.09820622],
       ...,
       [ 0.27332473, -0.13436131,  0.1542285 , ...,  0.05002733,
         0.03555092,  0.10489374],
       [ 0.4294793 , -0.10777918,  0.12475884, ...,  0.22315489,
         0.13328613,  0.07689492],
       [ 0.41516918, -0.29625255, -0.02715374, ...,  0.14360304,
         0.01678687,  0.04616653]], dtype=float32)

In [31]:
print(len(nasa_tweets_vec))
print(len(jeff_tweets_vec))

105
186


In [33]:
print(nasa_tweets_vec.shape)
print(jeff_tweets_vec.shape)

(105, 96)
(186, 96)


In [34]:
vects = np.vstack([nasa_tweets_vec, jeff_tweets_vec])

In [35]:
vects.shape

(291, 96)

In [37]:
labels = np.concatenate([np.zeros(len(nasatwee)), np.ones(len(jefftwee))])
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
log_reg = LogisticRegression().fit(vects, labels)

In [40]:
some_text = "Let's go to the moon!"

In [43]:
some_text_vec = nlp(some_text).vector
len(some_text_vec)

96

In [45]:
some_text_vec = some_text_vec.reshape(1, -1)

In [46]:
log_reg.predict(some_text_vec)

array([1.])

In [47]:
def test_tweet(text):
    vectored = nlp(text).vector
    reshaped = vectored.reshape(1, -1)

    return log_reg.predict(reshaped)[0]

In [77]:
print(test_tweet('Bruh'))

1.0


In [78]:
import pickle

In [80]:
pickle.dump(log_reg, open('my_log_reg_model.sav', 'wb'))

In [81]:
loaded_model = pickle.load(open('my_log_reg_model.sav', 'rb'))

In [82]:
loaded_model.predict(some_text_vec)

array([1.])

In [83]:
biden = twitter.get_user('joebiden')

In [84]:
bidetwee = biden.timeline(count=200, exclude_replies=True, include_rts=False, tweet_mode='Extended')

In [101]:
print(bidetwee)

[Status(_api=<tweepy.api.API object at 0x7ffb4d298400>, _json={'created_at': 'Tue Sep 14 21:00:26 +0000 2021', 'id': 1437883965168312322, 'id_str': '1437883965168312322', 'text': 'California, the eyes of the nation are on you. Vote NO on the recall before polls close at 8pm to keep @GavinNewsom… https://t.co/OL8LakaKKy', 'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'GavinNewsom', 'name': 'Gavin Newsom', 'id': 11347122, 'id_str': '11347122', 'indices': [103, 115]}], 'urls': [{'url': 'https://t.co/OL8LakaKKy', 'expanded_url': 'https://twitter.com/i/web/status/1437883965168312322', 'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]}, 'source': '<a href="https://sproutsocial.com" rel="nofollow">Sprout Social</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 939091, 'id_str': '939091', 'name

In [85]:
bide_tweets_vec = np.array([vec(tweet.text) for tweet in bidetwee])

In [100]:
bide_tweets_vec.shape
nasa_tweets_vec.shape

(105, 96)

In [86]:
vects = np.vstack([nasa_tweets_vec, bide_tweets_vec])
labels = np.concatenate([np.zeros(len(nasatwee)), np.ones(len(bidetwee))])
log_reg = LogisticRegression().fit(vects, labels)

In [98]:
test_tweet('I am literally Joe Biden')

0.0